services:
  vulnai:                
    container_name: vulnai 
    build:
      context: .           
      dockerfile: Dockerfile  
    ports:
      - "5003:5000"       
    volumes:
      - .:/app            
    environment:
      FLASK_ENV: development
      FLASK_APP: web/app.py
    depends_on:
      - mysql
    command: ["flask", "run", "--host=0.0.0.0", "--debug"]

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"  # Exponer la API en el puerto 5001
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      FLASK_APP: api/app.py  # Ruta al archivo de la API
    depends_on:
      - mysql
    command: ["flask", "run", "--host=0.0.0.0", "--debug"]

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: vulnai_db
      MYSQL_USER: vulnai
      MYSQL_PASSWORD: xmw1pW9CPyI4xKSN
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: vulnai
      PMA_PASSWORD: xmw1pW9CPyI4xKSN
    ports:
      - "8080:80"
    depends_on:
      - mysql