SQLALCHEMY_DATABASE_URI = "mariadb+mariadbconnector://usuario:password@mariadb:3306/vulnai_db"
SQLALCHEMY_TRACK_MODIFICATIONS = false
SECRET_KEY = "8dc6ce8d917c3cfacbaf7c018f730813366ccb3d80e30e5d6fa810823ef49097"